name: FirstWorkflow

on: push

jobs:
  steup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GH-200 session!!!"
   
      - name: List files
        run: ls -la

      - name: Generate ASCII Art
        run: |
         chmod +x scripts/greet.sh
         ./scripts/greet.sh
         
