name: FirstWorkflow

on: push

jobs:
  steup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GH-200 session!!!"

      - name: Copy Code 
        uses: actions/checkout@v5
      
      - name: List files
        run: ls -la

      - name: Generate ASCII Art
        run: |
          sudo apt-get install -y figlet
          figlet "GH-200 COHACK"
          echo "---------------------------"
          figlet -f digital "GitHub Actions"
