name: FirstWorkflow

on: push

jobs:
  steup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GH-200 session!!!"

      - name: Copy Code 
        uses: actions/checkout@v5
      
      - name: List files
        run: ls -la
